name: Mulled Unit Tests
on:
  issue_comment:
    types: [created]
jobs:
  test:
    name: Test
    if: github.event.user == gx-workflow-app
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      run: echo hi
