name: App test
on:
  issue_comment:
    types: [created]
jobs:
  test:
    name: Test
    if: github.actor == 'gx-workflow-app[bot]'
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - run: echo hi
